apiVersion: v1
kind: Namespace
metadata:
  name: flask-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: flask-app
data:
  FLASK_ENV: "development"
  AWS_REGION: "us-west-1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-upload-app
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-upload-app
  template:
    metadata:
      labels:
        app: flask-upload-app
    spec:
      containers:
      - name: flask-app
        image: flask-upload-app:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: FLASK_ENV
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: AWS_REGION
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-app
spec:
  selector:
    app: flask-upload-app
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
